version: '3.4'
services:
  exist:
    image: ${EXIST_IMAGE}:${EXIST_TAG}
    container_name: ex
    hostname: exhost
    ports:
      - 8080:8080
    networks:
      - www
    volumes:
      - type: volume
        source: data
        target: ${EXIST_HOME}/${EXIST_DATA_DIR}
  openresty:
    image: ${OPENRESTY_IMAGE}:${OPENRESTY_TAG}
    container_name: or
    hostname: orhost
    depends_on:
      - "exist"
    environment:
      - EXIST_AUTH=${EXIST_AUTH}
    ports:
      - 80:80
      - 443:443
    networks:
      - www
    volumes:
      - type: volume
        source: html
        target: ${OPENRESTY_HOME}/nginx/html
      - type: volume
        source: conf
        target: ${OPENRESTY_HOME}/nginx/conf
      - type: volume
        source: site
        target: ${OPENRESTY_HOME}/site
      - type: volume
        source: letsencrypt
        target: ${LETSENCRYPT}
volumes:
  data:
    driver: local
    name: data
  site:
    driver: local
    name: site
  conf:
    driver: local
    name: conf
  html:
    driver: local
    name: html
  letsencrypt:
    driver: local
    name: letsencrypt
networks:
  www:
    driver: bridge
