version: '3.7'
services:
  openresty:
    volumes:
      - type: bind
        source: ./bin
        target: ${OPENRESTY_HOME}/site/bin
      - type: bind
        source: ./t
        target: ${OPENRESTY_HOME}/t
    environment:
      - DOMAIN=${DOMAIN}
