version: '3.7'
services:
  exist:
    image: ${EXIST_IMAGE}:${EXIST_TAG}
    container_name: ex
    hostname: exDev
    ports:
      - 8080:8080
    volumes:
      - type: volume
        source: data
        target: ${EXIST_HOME}/${EXIST_DATA_DIR}
    secrets:
      - gmack_nz_access_token
      - gmack_nz_twitter_credentials
  openresty:
    image: ${OPENRESTY_IMAGE}:${OPENRESTY_TAG}
    container_name: or
    hostname: orhost
    depends_on:
      - "exist"
    environment:
      - EXIST_AUTH=${EXIST_AUTH}
      - TLS_COMMON_NAME=${TLS_COMMON_NAME}
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: volume
        source: html
        target: ${OPENRESTY_HOME}/nginx/html
      - type: volume
        source: conf
        target: ${OPENRESTY_HOME}/nginx/conf
      - type: volume
        source: site
        target: ${OPENRESTY_HOME}/site
      - type: volume
        source: letsencrypt
        target: ${LETSENCRYPT}
    secrets:
      - gmack_nz_access_token
volumes:
  data:
    driver: local
    name: data
  site:
    driver: local
    name: site
  conf:
    driver: local
    name: conf
  html:
    driver: local
    name: html
  letsencrypt:
    driver: local
    name: letsencrypt
secrets:
  gmack_nz_access_token:
    file: ./secrets/gmack_nz_access_token
  gmack_nz_twitter_credentials:
    file: ./secrets/gmack_nz_twitter_credentials

